app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('login_and_register.urls')),
    path('likes/', include('likes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.index, name="index"),
    path('posts/<int:pk>',views.detail,name="post_detail"),
]

login_and_register/urls.py
from django.urls import path
from . import views

app_name = "login_and_register"
urlpatterns = [
    path("register/", views.user_register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
]

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.core.exceptions import ValidationError
from PIL import Image
from image_cropping import ImageRatioField

# Create your models here.


class User(AbstractUser):
    is_writer = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.is_writer == False:
            try:
                profil = UserProfil.objects.get(user=self.id)
            except UserProfil.DoesNotExist:
                #uwazac tu musze instancje podac
                UserProfil.objects.create(user=self)
        else:
            try:
                profil = WriterProfil.objects.get(user=self.id)
            except WriterProfil.DoesNotExist:
                WriterProfil.objects.create(user=self)


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField("Post")

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(
        "WriterProfil", on_delete=models.SET_NULL, null=True, blank=False
    )
    title = models.CharField(max_length=255)
    category = models.ForeignKey(
        "Category", on_delete=models.SET_NULL, null=True, blank=False
    )
    sneekpeek = models.TextField()
    content = models.TextField()
    image = models.ImageField(upload_to="images/")
    cropping = ImageRatioField("image", "730x390")
    # auto_add_now - hard to test later with mock data
    created_at = models.DateTimeField(default=timezone.now)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]

    def clean(self):
        if self.is_featured == True:
            if Post.objects.filter(is_featured=True).count() >= 5:
                ownInst = Post.objects.get(pk=self.id)
                if ownInst and ownInst.is_featured == True:
                    return
                raise ValidationError("There cannot be more than 5 featured articles")

    def __str__(self):
        return self.title

    def get_tags(self):
        return "\n".join([p.name for p in self.tag_set.all()])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Call the "real" save() method.
        if self.image:
            pass
            # image = Image.open(self.image)
            # width, height = image.size
            # left = (width - 730)/2
            # top = (height - 390)/2
            # right = (width + 730)/2
            # bottom = (height + 390)/2
            # # resized_image = image.resize((750,400))
            # resized_image = image.crop((left,top,right,bottom))
            # resized_image.save(self.image.path)

    # Overwriting get_tags name display in django admin
    get_tags.short_description = "Tags"


class Like(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    profil = models.ForeignKey("UserProfil", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("post", "profil")


class AbstractProfil(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, blank=False)
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # Dont generate additional table
    class Meta:
        abstract = True


class WriterProfil(AbstractProfil):
    def __str__(self):
        return self.user.username

    def clean(self):
        if self.user.is_writer == False:
            raise ValidationError("User is a writer")

    def save(self, *args, **kwargs):
        print("save")
        super().save(*args, **kwargs)
        print("saveed")

    class Meta:
        verbose_name_plural = "Writer Profiles"


class UserProfil(AbstractProfil):
    posts = models.ManyToManyField("Post", through="Like")

    def __str__(self):
        return self.user.username

    def clean(self):
        if self.user.is_writer == True:
            raise ValidationError("User cannot be writer")

    class Meta:
        verbose_name_plural = "User Profiles"

core/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from comments.forms import CommentAnonForm, CommentForm

# Create your views here.


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get("page", 1)

    categories = Category.objects.all()
    tags = Tag.objects.all()
    liked_posts = (
        Post.objects.all().annotate(likes_count=Count("like")).order_by("-likes_count")
    )
    featured_posts = Post.objects.filter(is_featured=True)
    context = {
        "posts": paginator.get_page(page),
        "categories": categories,
        "tags": tags,
        "liked_posts": liked_posts,
        "featured_posts": featured_posts,
    }
    return render(request, "core/index.html", context)


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    tags = Tag.objects.all()
    liked_posts = (
        Post.objects.all().annotate(likes_count=Count("like")).order_by("-likes_count")
    )
    categories = Category.objects.all()
    context = {
        "post": post,
        "categories": categories,
        "tags": tags,
        "liked_posts": liked_posts
    }

    if request.method == "POST":
        comment = request.POST.copy()
        comment['post'] = post.id
        if request.user:
            comment['user'] = request.user.id
        form = CommentForm(comment)
        if form.is_valid():
            # some logic
            form.save()
            return redirect('blog:post_detail', pk)
    else:
        form = CommentForm()

    context['form'] = form
    return render(request, "core/detail.html", context)

core/templates/core/includes/footer.html
<footer class="footer-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore dolore
                        magna aliqua.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                    required="" type="email">


                                <button class="click-btn btn btn-default"><span
                                        class="lnr lnr-arrow-right"></span></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                        type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                              </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="img/instagram/i1.jpg" alt=""></li>
                        <li><img src="img/instagram/i2.jpg" alt=""></li>
                        <li><img src="img/instagram/i3.jpg" alt=""></li>
                        <li><img src="img/instagram/i4.jpg" alt=""></li>
                        <li><img src="img/instagram/i5.jpg" alt=""></li>
                        <li><img src="img/instagram/i6.jpg" alt=""></li>
                        <li><img src="img/instagram/i7.jpg" alt=""></li>
                        <li><img src="img/instagram/i8.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-dribbble"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-behance"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                    target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>

core/templates/core/includes/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sensive Blog - Home</title>
    <link rel="icon" href="img/Fevicon.png" type="image/png">

    <link rel="stylesheet" href='{% static "core/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "core/vendors/fontawesome/css/all.min.css" %}'>
    <link rel="stylesheet" href='{% static "core/css/style.css" %}'>
    <link rel="stylesheet" href='{% static "core/vendors/themify-icons/themify-icons.css" %}'>
    <link rel="stylesheet" href='{% static "core/vendors/linericon/style.css" %}'>
    <link rel="stylesheet" href='{% static "core/vendors/owl-carousel/owl.theme.default.min.css" %}'>
    <link rel="stylesheet" href='{% static "core/vendors/owl-carousel/owl.carousel.min.css" %}'>
    <link rel="stylesheet" href='{% static "core/css/custom.css" %}'>


</head>

core/templates/core/includes/header.html
{% load static %}
{% load core_extras %}
<header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container box_1620">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" href="index.html"><img src="{% static 'core/img/logo.png' %}" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    {% navigation %}
                        <ul class="nav navbar-nav navbar-right navbar-social">
                            <li><a href="#"><i class="ti-facebook"></i></a></li>
                            <li><a href="#"><i class="ti-twitter-alt"></i></a></li>
                            <li><a href="#"><i class="ti-instagram"></i></a></li>
                            <li><a href="#"><i class="ti-skype"></i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>

core/templates/core/includes/hero.html
<section class="mb-30px">
        <div class="container">
            <div class="hero-banner">
                <div class="hero-banner__content">
                    <h3>Tours & Travels</h3>
                    <h1>Amazing Places on earth</h1>
                    <h4>December 12, 2018</h4>
                </div>
            </div>
        </div>
    </section>

core/templates/core/includes/navigation.html
<ul class="nav navbar-nav menu_nav justify-content-center">
    <li class="nav-item active"><a class="nav-link" href="{% url 'blog:index'%}">Home</a></li>
    <li class="nav-item submenu dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">Category</a>
        <ul class="dropdown-menu">
            <li class="nav-item"><a class="nav-link" href="blog-details.html">Blog Details</a></li>
        </ul>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'login_and_register:logout' %}">Logout</a></li>
    {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'login_and_register:login' %}">Login</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'login_and_register:login' %}">Register</a></li>
    {% endif %}
        
</ul>

core/templates/core/includes/sidebar.html
<div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
            <div class="single-sidebar-widget newsletter-widget">
                <h4 class="single-sidebar-widget__title">Newsletter</h4>
                <div class="form-group mt-30">
                    <div class="col-autos">
                        <input type="text" class="form-control" id="inlineFormInputGroup"
                            placeholder="Enter email" onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Enter email'">
                    </div>
                </div>
                <button class="bbtns d-block mt-20 w-100">Subcribe</button>
            </div>


            <div class="single-sidebar-widget post-category-widget">
                <h4 class="single-sidebar-widget__title">Catgory</h4>
                <ul class="cat-list mt-20">
                    
                    {% for category in categories  %}
                    <li>
                        <a href="#" class="d-flex justify-content-between">
                            <p>{{category.name}}</p>
                            <p>{{category.post_set.count}}</p>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="single-sidebar-widget popular-post-widget">
                <h4 class="single-sidebar-widget__title">Popular Post</h4>
                <div class="popular-post-list">
                    
                    {% for post in liked_posts  %}
                    <div class="single-post-list">
                        <div class="thumb">
                            <img class="card-img rounded-0" src="{{post.image.url}}" alt="">
                            <ul class="thumb-info">
                                <li><a href="#">{{post.author}}</a></li>
                                <li><a href="#">{{post.created_at | date:"M d"}}</a></li>
                                <li><a href="#">{{post.likes_count}}</a></li>
                                <!-- <li><a href="#">{{post.likes_count}}</a></li> -->
                            </ul>
                        </div>
                        <div class="details mt-20">
                            <a href="blog-single.html">
                                <h6>{{post.title}}</h6>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                        
                </div>
            </div>

            <div class="single-sidebar-widget tag_cloud_widget">
                <h4 class="single-sidebar-widget__title">Tags</h4>
                <ul class="list">
                    
                    {% for tag in tags  %}
                    <li>
                        <a href="#">{{tag.name}}</a>
                    </li>
                    {% endfor %}
                        
                </ul>
            </div>
        </div>
    </div>

core/templates/core/includes/slider.html
{% load humanize %}
{% load cropping %}
<section>
    <div class="container">
        <div class="owl-carousel owl-theme blog-slider">

            {% for post in featured_posts  %}
            <div class="card blog__slide text-center">
                <div class="blog__slide__img">
                    <img class="card-img rounded-0" src="{% cropped_thumbnail post 'cropping' scale=1 %}" alt="">
                </div>
                <div class="blog__slide__content">
                    <a class="blog__slide__label" href="#">{{post.category.name}}</a>
                    <h3><a href="#">{{post.title}}</a></h3>
                    <p>{{post.created_at | timesince}}</p>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>